# Generated by Django 4.2.7 on 2024-05-10 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                ("is_safe_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("route_name", models.CharField(max_length=100, unique=True)),
                ("destination", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("num_seats", models.IntegerField(default=25)),
                ("capacity", models.IntegerField(default=0)),
                ("plate_number", models.CharField(max_length=20)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_routes",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
