# Generated by Django 4.2.7 on 2024-05-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subscription_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reservation_amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=0)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bus_route', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bus_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_subscriptions', to='bus.busoffering')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_subscriptions', to='bus.busroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('map_location', models.CharField(max_length=255)),
                ('departure_time', models.TimeField(verbose_name='Departure Time')),
                ('arrival_time', models.TimeField(verbose_name='Arrival Time')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_stops', to='bus.busroute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('destination', models.CharField(choices=[('From University', 'From University'), ('To University', 'To University')], max_length=20)),
                ('bus_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_reservation', to='bus.busoffering')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_reservation', to='bus.busroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
