# Generated by Django 4.2.7 on 2024-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busroute",
            name="num_seats",
        ),
        migrations.AlterField(
            model_name="busroute",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="busroute",
            name="destination",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="busroute",
            name="plate_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
