# Generated by Django 4.2.7 on 2024-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0003_remove_busroute_route_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busroute",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
