# Generated by Django 4.2.7 on 2024-05-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bus", "0005_busstop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="bus_route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bus_stops",
                to="bus.busroute",
            ),
        ),
    ]
