# Generated by Django 4.2.7 on 2024-05-10 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bus", "0005_busstop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="bus_route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bus_stops",
                to="bus.busroute",
            ),
        ),
        migrations.CreateModel(
            name="BusChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_safe_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                (
                    "bus_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bus.busroute"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
