# Generated by Django 4.2.7 on 2024-05-17 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0005_busstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='bus_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_stops', to='bus.busroute'),
        ),
    ]
