# Generated by Django 4.2.7 on 2024-05-17 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0006_alter_busroute_driver_alter_busstop_bus_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_subscriptions', to='bus.busroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
