# Generated by Django 4.2.7 on 2024-05-18 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0007_bussubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subscription_amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='busroute',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bus_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bus_routes', to='bus.busoffering'),
            preserve_default=False,
        ),
    ]
