# Generated by Django 4.2.7 on 2024-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "semester_name",
                    models.CharField(
                        choices=[("Fall", "Fall"), ("Spring", "Spring")], max_length=10
                    ),
                ),
                ("subscribe_valid_from", models.DateField()),
                ("subscribe_valid_to", models.DateField()),
            ],
            options={
                "unique_together": {("year", "semester_name")},
            },
        ),
    ]
