# Generated by Django 4.2.7 on 2024-05-16 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0003_delete_semester"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
