# Generated by Django 4.2.7 on 2024-05-16 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
